"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

# REPLACE BASED ON WHICH
APP = ['.py']
DATA_FILES = []

# For STANDALONE, comment out for TROJAN setup
# OPTIONS = {'iconfile': '/images/icon.icns', 'plist': { 'LSUIElement': True, }, }

# No icon STANDALONE
# OPTIONS = {'plist': { 'LSUIElement': True, }, }

# For TROJAN, comment out for STANDALONE setup
OPTIONS = {'iconfile': '/images/icon2.icns',}

# No icon TROJAN
# OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
